"""business professional directory cms

Revision ID: 7989310265ab
Revises: 50e7fc33e83d
Create Date: 2026-09-28 04:30:28.035884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7989310265ab'
down_revision = '50e7fc33e83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_directory_categories_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directory_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directory_categories_slug'), ['slug'], unique=True)

    op.create_table('directory_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('listing_type', sa.String(length=30), nullable=False),
    sa.Column('ownership_classification', sa.String(length=20), nullable=False),
    sa.Column('classification_provenance', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_summary', sa.Text(), nullable=True),
    sa.Column('key_services', sa.JSON(), nullable=False),
    sa.Column('service_modes', sa.JSON(), nullable=False),
    sa.Column('public_contact_email', sa.String(length=255), nullable=True),
    sa.Column('public_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('featured_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('featured_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification_provenance IN ('self_attested', 'staff_reviewed')", name='ck_directory_listings_classification_provenance'),
    sa.CheckConstraint("listing_type IN ('business', 'nonprofit', 'professional_service', 'social_enterprise', 'association')", name='ck_directory_listings_listing_type'),
    sa.CheckConstraint("ownership_classification IN ('women_owned', 'women_led', 'women_founded', 'women_focused', 'unspecified')", name='ck_directory_listings_ownership_classification'),
    sa.CheckConstraint("status IN ('pending', 'under_review', 'approved', 'published', 'rejected', 'archived')", name='ck_directory_listings_status'),
    sa.CheckConstraint("verification_status IN ('unverified', 'self_attested', 'reviewed', 'verified')", name='ck_directory_listings_verification_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directory_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directory_listings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_listings_organization_id'), ['organization_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_directory_listings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_listings_verification_status'), ['verification_status'], unique=False)

    op.create_table('directory_listing_categories',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['directory_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['directory_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'category_id')
    )
    op.create_table('directory_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_name_normalized', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('website_domain', sa.String(length=255), nullable=True),
    sa.Column('listing_type', sa.String(length=30), nullable=False),
    sa.Column('ownership_classification', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_services', sa.JSON(), nullable=False),
    sa.Column('service_modes', sa.JSON(), nullable=False),
    sa.Column('category_ids', sa.JSON(), nullable=False),
    sa.Column('public_contact_email', sa.String(length=255), nullable=True),
    sa.Column('public_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('submitter_name', sa.String(length=200), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=False),
    sa.Column('submitter_role', sa.String(length=120), nullable=True),
    sa.Column('possible_duplicate_organization_id', sa.Integer(), nullable=True),
    sa.Column('matched_organization_id', sa.Integer(), nullable=True),
    sa.Column('resulting_listing_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'matched', 'duplicate', 'converted', 'rejected')", name='ck_directory_submissions_status'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['matched_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['possible_duplicate_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resulting_listing_id'], ['directory_listings.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directory_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directory_submissions_business_name_normalized'), ['business_name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_submissions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_directory_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_submissions_website_domain'), ['website_domain'], unique=False)

    op.create_table('directory_submission_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['directory_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected unrelated drift between models and
    # the live schema (search-vector/status index diffs on Article/Event/
    # Job/Opportunity/People/Resource, a Media FK, Newsletter/Pages
    # constraint-vs-index duplication, Partnership/Sponsor index dupes) —
    # pre-existing and out of this Directory-CMS-only task's scope, so it's
    # pruned here rather than folded into this migration.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directory_submission_notes')
    with op.batch_alter_table('directory_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directory_submissions_website_domain'))
        batch_op.drop_index(batch_op.f('ix_directory_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_directory_submissions_reference'))
        batch_op.drop_index(batch_op.f('ix_directory_submissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_directory_submissions_business_name_normalized'))

    op.drop_table('directory_submissions')
    op.drop_table('directory_listing_categories')
    with op.batch_alter_table('directory_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directory_listings_verification_status'))
        batch_op.drop_index(batch_op.f('ix_directory_listings_status'))
        batch_op.drop_index(batch_op.f('ix_directory_listings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_directory_listings_created_at'))

    op.drop_table('directory_listings')
    with op.batch_alter_table('directory_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directory_categories_slug'))

    op.drop_table('directory_categories')
    # ### end Alembic commands ###
