"""add users.must_change_password — forced first-login password change for
CMS staff accounts created with (or reset to) a temporary password

Revision ID: 950a29bb1ce9
Revises: 9c1d7e4b2a6f
Create Date: 2026-10-02 00:00:00.000000

Hand-written rather than autogenerated: this repo's users/media tables
have a circular FK (media.uploaded_by_id -> users.id, users.avatar_media_id
-> media.id, each declared with use_alter=True to break the cycle at
create-table time) that has previously made `alembic revision --autogenerate`
emit phantom drop/add FK operations against that cycle. This migration
contains only the one intentional column addition below — no FK operations
of any kind.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '950a29bb1ce9'
down_revision = '9c1d7e4b2a6f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
